name: Create Build and Release ACTION_BRANCH

on:
  push:
    branches:
      - actions-branch
jobs:
  release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: static-site
      - name: echo
        run: echo ${{steps.download.outputs.download-path}}

      - name: ZIP Build
        id: zip-release
        uses: thedoctor0/zip-release@master
        with: 
          type: zip
          filename: static-site.zip
      - name: Print Current Working Directory
        id: pwd_step
        run: |
          current_dir=$(pwd)
          echo "Current Working Directory: $current_dir"
          echo "::set-output name=current_dir::$current_dir"
      - name: List contents of the directory
        run: | 
          ls ${{steps.pwd_step.outputs.current_dir}}
      - name: Check if file exists
        run: |
          if test -e /home/runner/work/Space-Rescue/Space-Rescue/static-site.zip; then
            echo "File exists"
            mkdir -p release
            mv /home/runner/work/Space-Rescue/Space-Rescue/static-site.zip release/static-site.zip
          else
            echo "Non existent file requested"
          fi
        id: check_file
      - name: list files in release folder
        run: ls ${{steps.pwd_step.outputs.current_dir}}/release
        
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
      - name: action-upload-release
        # You may pin to the exact commit or the version.
        # uses: diamondburned/action-upload-release@7db8db63a78c06f926781e117394719b303ddfc7
        uses: diamondburned/action-upload-release@v0.0.1
        with:
          files: ./release/static-site.zip 
          # The release ID to upload to. This is optional if the event that triggered
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Print Current Working Directory
        run: pwd
      - name: list the Current Working Directory using ls
        run: ls
      - name: list the CWD using ls -a
        run: ls -a


      # Build
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      # Output
      - name: Upload static site
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: .next/
          
      - name: Print Current Working Directory
        run: pwd
      - name: list the Current Working Directory using ls
        run: ls
      - name: list the CWD using ls -a
        run: ls -a     
