name: Automate Testing

on:
  push:
    branches-ignore: [main] #Formatting will not be checked on main because It should already be formatted and I dont want a commit to trigger the release workflow

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        testMode:
          - editmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ./Library
          key: Library-Space-Rescue-TargetPlatform
          restore-keys: |
            Library-Space-Rescue-
            Library-
      - name: print files directory
        run: | 
          ls ${{ matrix.projectPath }}
      - uses: game-ci/unity-test-runner@v3.0.0
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}

    
