---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: MegaLinter

on:
  # Trigger mega-linter at every push. Action will also be visible from Pull Requests to main
  push:
    branches-ignore: [master, main]
    paths:
        - "**.cs"
        - ".editorconfig"
        - "validation.yml"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
      - name: show git diff
        run: |
          dotnet restore Space-Rescue.sln
          dotnet restore Assembly-CSharp.csproj
          git diff ${{github.event.before}} --name-only
          
          dotnet format Space-Rescue.sln --include $( git diff ${{github.event.before}} --name-only)  --verify-no-changes --no-restore --verbosity diagnostic


